ALTER TABLE users ADD COLUMN IF NOT EXISTS total_watches INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS milestones_claimed SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_daily_bonus_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_7_bonus_claimed BOOLEAN NOT NULL DEFAULT FALSE;
